# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 21:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('dia', models.DateField(primary_key=True, serialize=False, unique=True, verbose_name='Data')),
            ],
        ),
        migrations.CreateModel(
            name='Voo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.TimeField(blank=True, help_text='Hora UTC (zulu) no formato 00:00', verbose_name='Horário')),
                ('cod_chamada', models.CharField(blank=True, max_length=20, verbose_name='Código de Chamada')),
                ('dianteiro', models.CharField(max_length=3, verbose_name='Dianteiro')),
                ('traseiro', models.CharField(blank=True, max_length=3, verbose_name='Traseiro')),
                ('codigo_oi', models.CharField(max_length=30, verbose_name='Código da OI')),
                ('tempo', models.TimeField(help_text='Tempo planejado de voo', verbose_name='Tempo')),
                ('area', models.CharField(blank=True, max_length=15, verbose_name='Área')),
                ('obs', models.CharField(blank=True, max_length=50, verbose_name='Obs')),
                ('hora_partida', models.TimeField(blank=True, help_text='Hora UTC que o piloto chamou para o acionamento', verbose_name='Partida')),
                ('hora_dep', models.TimeField(blank=True, help_text='Hora UTC da decolagem real da aeronave', verbose_name='Decolagem')),
                ('hora_pso', models.TimeField(blank=True, help_text='Hora UTC do pouso real da aeronave', verbose_name='Pouso')),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escavoos.Data')),
            ],
        ),
    ]
