# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escavoos', '0003_auto_20161127_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voo',
            name='area',
            field=models.CharField(blank=True, default='OCE', max_length=15, verbose_name='área'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voo',
            name='cod_chamada',
            field=models.CharField(blank=True, max_length=20, verbose_name='código de Chamada'),
        ),
        migrations.AlterField(
            model_name='voo',
            name='hora_dep',
            field=models.TimeField(blank=True, help_text='Hora UTC da decolagem real da aeronave', verbose_name='decolagem'),
        ),
        migrations.AlterField(
            model_name='voo',
            name='hora_partida',
            field=models.TimeField(blank=True, help_text='Hora UTC que o piloto chamou para o acionamento', verbose_name='partida'),
        ),
        migrations.AlterField(
            model_name='voo',
            name='hora_pso',
            field=models.TimeField(blank=True, help_text='Hora UTC do pouso real da aeronave', verbose_name='pouso'),
        ),
        migrations.AlterField(
            model_name='voo',
            name='horario',
            field=models.TimeField(blank=True, help_text='Hora UTC (zulu) no formato 00:00', verbose_name='horário'),
        ),
        migrations.AlterField(
            model_name='voo',
            name='obs',
            field=models.CharField(blank=True, max_length=50, verbose_name='obs'),
        ),
        migrations.AlterField(
            model_name='voo',
            name='traseiro',
            field=models.CharField(blank=True, max_length=3, verbose_name='traseiro'),
        ),
    ]
