# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escavoos', '0004_auto_20161127_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voo',
            name='hora_dep',
            field=models.TimeField(blank=True, help_text='Hora UTC da decolagem real da aeronave', null=True, verbose_name='decolagem'),
        ),
        migrations.AlterField(
            model_name='voo',
            name='hora_partida',
            field=models.TimeField(blank=True, help_text='Hora UTC que o piloto chamou para o acionamento', null=True, verbose_name='partida'),
        ),
        migrations.AlterField(
            model_name='voo',
            name='hora_pso',
            field=models.TimeField(blank=True, help_text='Hora UTC do pouso real da aeronave', null=True, verbose_name='pouso'),
        ),
    ]
