# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escavoos', '0005_auto_20161127_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='voo',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voo',
            name='data',
            field=models.DateField(verbose_name='data'),
        ),
    ]
