# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escavoos', '0006_auto_20161127_1243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voo',
            options={'ordering': ('id',), 'verbose_name_plural': 'Voos'},
        ),
        migrations.AddField(
            model_name='voo',
            name='abortado_solo',
            field=models.BooleanField(default=False),
        ),
    ]
